version: 0.2
env:
  variables:
    GOOS: darwin
    GOARCH: amd64

phases:
  install:
    commands:
      - echo "hello from install"
      - go version # Check Go version
      - pwd # Confirm working directory
      - ls -la # List files
  pre_build:
    commands:
      - echo "hello from pre_build"
  build:
    commands:
      - echo "Substituting environment variables in hello-world.go"
      - mv hello-world.go hello-world.go.tmp # Rename file to .tmp
      - envsubst < hello-world.go.tmp > hello-world.go
      - echo "Building Go application"
      - go build hello-world.go # Correct build command
  post_build:
    commands:
      - echo "hello from post_build"

artifacts:
  files:
    - "hello-world"
    - "README.txt"
  name: hello-app-$(date +%Y-%m-%d).zip
