version: 0.2
env:
  variables:
    GOOS: darwin
    GOARCH: amd64

phases:
  install:
    commands:
      - echo "hello from install"
      - go version # Ensure Go is installed and display the version
  pre_build:
    commands:
      - echo "hello from pre_build"
  build:
    commands:
      - echo "Substituting environment variables in hello-world.go"
      - envsubst < hello-world.go.tmp > hello-world.go # Fix envsubst usage
      - echo "Building Go application"
      - go build -o hello-world hello-world.go # Output the binary as hello-world
  post_build:
    commands:
      - echo "hello from post_build"

artifacts:
  files:
    - "hello-world"
    - "README.txt"
  name: hello-app-$(date +%Y-%m-%d).zip
